import type { BuildStep, HardwareItem, Part, ProjectTemplate } from "./types";
import { dim } from "./parametric";

const { W, D, H, F } = dim;

function part(
  partial: Omit<Part, "stock" | "grain"> & { stock?: Part["stock"]; grain?: Part["grain"] },
): Part {
  return {
    stock: "solid",
    grain: "length",
    ...partial,
  };
}

const benchHardware: HardwareItem[] = [
  {
    id: "kreg-125",
    name: "Pocket-hole screws",
    qty: 24,
    spec: "1¼\" fine-thread, #8, square drive",
    aisle: "Kreg / wood joinery",
    forRoutes: ["pocket"],
  },
  {
    id: "glue",
    name: "Wood glue",
    qty: 1,
    spec: "Titebond II, 8 oz (I indoors) or III (damp shop)",
    aisle: "Adhesives",
  },
  {
    id: "figure8",
    name: "Figure-8 desktop fasteners",
    qty: 6,
    spec: "Zinc, with #6 × ⅝\" screws",
    aisle: "Tabletop hardware",
    forRoutes: ["pocket", "mortise"],
  },
  {
    id: "dowel",
    name: "Fluted dowels",
    qty: 16,
    spec: "⅜\" × 1½\"",
    aisle: "Joinery",
    forRoutes: ["dowel"],
  },
];

const benchSteps: BuildStep[] = [
  {
    id: "b1",
    title: "Pick and mill the stock",
    body: "Choose straight boards. Joint and plane to thickness, or pick S4S and check thickness with calipers — a ¾\" 1× is often ¾ on the nose, sometimes 11/16. Cut the top glue-up oversized by ½\" in both directions.",
    techniques: ["glue-up", "square-cut"],
  },
  {
    id: "b2",
    title: "Glue the top",
    body: "Dry-clamp the top boards. Grain runs the length of the bench. Glue, clamp, wait. Scrape the bead, then rip and crosscut the panel to final width and length.",
    techniques: ["glue-up"],
  },
  {
    id: "b3",
    title: "Cut legs and aprons",
    body: "Legs are square. Cut them a hair long, then shoot or sand to identical length — a bench with one short leg will rock forever. Cut aprons to the lengths on the cut list. Mark face sides.",
    techniques: ["square-cut"],
  },
  {
    id: "b4p",
    title: "Pocket-hole the aprons",
    body: "Two pocket holes on each end of every apron, on the inside face. Set the jig to actual apron thickness. The long aprons run between the legs; short aprons too. Dry-fit the base and check diagonals.",
    techniques: ["pocket-hole", "clamp-up"],
    forRoutes: ["pocket"],
  },
  {
    id: "b4d",
    title: "Dowel the aprons",
    body: "Two ⅜\" dowels per joint, offset so they can't spin. Drill with a jig. Glue and clamp the base, check diagonals, wait.",
    techniques: ["clamp-up"],
    forRoutes: ["dowel"],
  },
  {
    id: "b4m",
    title: "Mortise the legs, tenon the aprons",
    body: "Mortises land ¾\" down from the top of each leg so a haunch can hide. Tenon thickness is ⅓ of the apron. Dry-fit all four corners, then glue one long side, then the other, then close the box.",
    techniques: ["mortise-tenon", "clamp-up"],
    forRoutes: ["mortise"],
  },
  {
    id: "b5",
    title: "Attach the top",
    body: "The top floats. Figure-8 fasteners in shallow mortises on the apron edge, or Z-clips in a groove. Front can be a tight screw; back must slot. Do not glue the top to the base.",
    techniques: ["wood-movement"],
  },
  {
    id: "b6",
    title: "Break edges and finish",
    body: "A 1/16\" chamfer on the top keeps the edge from crumbling. Sand 120-180-220. Oil if it's maple or walnut; paint if it's poplar or pine.",
    techniques: ["finish-oil"],
  },
];

const consoleHardware: HardwareItem[] = [
  {
    id: "slides",
    name: "Side-mount drawer slides",
    qty: 2,
    spec: "12\" or 14\" full-extension, 100 lb, pair",
    aisle: "Drawer hardware",
  },
  {
    id: "knobs",
    name: "Drawer knobs or pulls",
    qty: 2,
    spec: "Brass, 1\"–1¼\" or 96 mm centers",
    aisle: "Cabinet hardware",
  },
  {
    id: "kreg-console",
    name: "Pocket-hole screws",
    qty: 32,
    spec: "1¼\" fine-thread #8",
    aisle: "Kreg / wood joinery",
    forRoutes: ["pocket"],
  },
  {
    id: "glue-c",
    name: "Wood glue",
    qty: 1,
    spec: "Titebond II, 16 oz",
    aisle: "Adhesives",
  },
  {
    id: "back-brads",
    name: "Brad nails",
    qty: 1,
    spec: "18 ga × ¾\" for the plywood back",
    aisle: "Fasteners",
  },
];

const consoleSteps: BuildStep[] = [
  {
    id: "c1",
    title: "Build the carcase",
    body: "Cut sides, top, bottom, and divider. The carcase is a box on legs — get it square before you think about drawers. Diagonals equal, inside opening measured in three places.",
    techniques: ["square-cut", "clamp-up"],
  },
  {
    id: "c2p",
    title: "Pocket-hole the box",
    body: "Pocket screws from the underside of the top into the sides, and through the bottom into the sides. A divider gets the same treatment. Glue every joint. This is honest shop furniture, not a hidden-fastener contest.",
    techniques: ["pocket-hole"],
    forRoutes: ["pocket"],
  },
  {
    id: "c2d",
    title: "Dado the sides for top, bottom, and divider",
    body: "Stopped dados on the inside of each side. Sneak up on the plywood-or-solid thickness. The back will cover the dado exits if you run them through.",
    techniques: ["dado"],
    forRoutes: ["dado"],
  },
  {
    id: "c3",
    title: "Taper and attach the legs",
    body: "Taper the two inside faces of each leg, leaving the top 3\" full. Attach with hanging bolts or a tight mortise into a corner block. Legs must sit coplanar — rock is fatal on a console.",
    techniques: ["taper-leg"],
  },
  {
    id: "c4",
    title: "Build drawer boxes",
    body: "Drawer boxes are 1\" narrower than the opening for ½\" side-mount slides, and ½–1\" shorter than the slide length. Bottoms sit in a ¼\" groove. False fronts get applied after the boxes run true.",
    techniques: ["drawer-slides", "square-cut"],
    forRoutes: ["pocket", "dado"],
  },
  {
    id: "c4v",
    title: "Dovetail the drawer boxes",
    body: "Half-blind dovetails at the front, through at the back, ¼\" bottom in a groove. Fit to the opening the slow way — a proud tail is easier to plane than a gap is to hide.",
    techniques: ["dovetail", "drawer-slides"],
    forRoutes: ["dovetail"],
  },
  {
    id: "c5",
    title: "Back, hardware, finish",
    body: "¼\" plywood back, glued and nailed into a rabbet — it squares the case. Install slides with spacer blocks. Oil walnut; don't stain it.",
    techniques: ["finish-oil", "drawer-slides"],
  },
];

export const CATALOG: ProjectTemplate[] = [
  {
    id: "bench",
    name: "Shaker bench",
    category: "bench",
    blurb: "Four legs, four aprons, a solid top. The right first furniture piece.",
    image: "/catalog/bench.jpg",
    overall: { w: 48, d: 14, h: 18 },
    thickness: 0.75,
    defaultSpecies: "maple",
    defaultRoute: "pocket",
    indoor: true,
    interpretation:
      "A Shaker-form bench: solid plank top, square legs, simple aprons. No stretchers, no back. Built as a floating top on a four-apron base so the top can move.",
    confidence: 0.92,
    uncertainties: [
      "Top thickness looks like ¾–4/4. Confirm before cutting legs.",
      "Leg dimension assumed 1½\" square — common, not visible from one photo.",
    ],
    routes: [
      {
        id: "pocket",
        name: "Pocket-hole base",
        recommendedRank: "beginner",
        summary: "Aprons screw into the legs from the inside. Fast, strong enough for a bench, fully repairable.",
        joinery: "Pocket holes + glue on aprons. Figure-8s for the top.",
        tools: ["Kreg jig", "miter or circular saw", "drill", "clamps"],
        tradeoffs: "Holes show on the inside. Not heirloom joinery. Perfectly good furniture.",
        hiddenWork: "The underside is pocketed; the show faces stay clean.",
      },
      {
        id: "dowel",
        name: "Dowel base",
        recommendedRank: "novice",
        summary: "Two dowels per joint. Cleaner inside than pocket holes, needs a jig and patience.",
        joinery: "⅜\" fluted dowels, glue, clamps.",
        tools: ["Dowel jig", "clamps", "saw"],
        tradeoffs: "No mechanical backup if you rush the glue-up. Dry-fit twice.",
        hiddenWork: "Joints disappear. Alignment is the whole game.",
      },
      {
        id: "mortise",
        name: "Mortise and tenon",
        recommendedRank: "craftsman",
        summary: "The correct joint for this piece if you want it to outlive you.",
        joinery: "Haunched M&T on all eight apron ends.",
        tools: ["Mortiser or chisels", "tenon saw", "marking gauge"],
        tradeoffs: "A full Saturday on joinery. Worth it in walnut or maple.",
        hiddenWork: "Haunch hides the mortise at the top of the leg.",
      },
    ],
    parts: [
      part({ id: "top", name: "Top panel", qty: 1, length: W(0), width: D(0), thickness: F(0.75), notes: "Glue up from 5–6\" boards, then cut to size." }),
      part({ id: "leg", name: "Leg", qty: 4, length: H(-0.75), width: F(1.5), thickness: F(1.5), notes: "Leave extra and batch-cut to identical length." }),
      part({ id: "apron-l", name: "Long apron", qty: 2, length: W(-3), width: F(3.5), thickness: F(0.75), notes: "Between 1½\" legs." }),
      part({ id: "apron-s", name: "Short apron", qty: 2, length: D(-3), width: F(3.5), thickness: F(0.75) }),
    ],
    hardware: benchHardware,
    steps: benchSteps,
  },
  {
    id: "console",
    name: "Walnut console",
    category: "case",
    blurb: "Low two-drawer console on tapered legs. The photo-to-packet test piece.",
    image: "/catalog/nightstand.jpg",
    overall: { w: 56, d: 16, h: 28 },
    thickness: 0.75,
    defaultSpecies: "walnut",
    defaultRoute: "pocket",
    indoor: true,
    interpretation:
      "A mid-century low console: two drawers over an open void, tapered legs, applied top. Interior construction is not visible — drawer boxes and the carcase joint are a choice, not a fact.",
    confidence: 0.78,
    uncertainties: [
      "Drawer-box method is invisible. Pick a route below.",
      "Leg attachment (hanger bolt vs. mortise) is inferred.",
      "Back is assumed ¼\" plywood in a rabbet.",
      "Overall size estimated from typical proportions unless you lock a dimension.",
    ],
    routes: [
      {
        id: "pocket",
        name: "Pocket-hole carcase, overlay drawers",
        recommendedRank: "beginner",
        summary: "Box built with pocket screws. Overlay false fronts hide a lot of sins. The version that gets the piece in the room.",
        joinery: "Pocket screws + glue. Side-mount slides. Screwed false fronts.",
        tools: ["Kreg jig", "circular/miter saw", "drill", "clamps"],
        tradeoffs: "Not period-correct. Overlay fronts are more forgiving than inset.",
        hiddenWork: "Everything behind the false fronts is shop-grade plywood if you want.",
      },
      {
        id: "dado",
        name: "Dadoed carcase, inset drawers",
        recommendedRank: "apprentice",
        summary: "Dados carry the load. Inset fronts need even gaps — a real test of a square case.",
        joinery: "Dados + glue, optional screws in the back. Inset fronts.",
        tools: ["Table saw or router", "dado stack or straight bit", "clamps"],
        tradeoffs: "Gaps on inset drawers tell on you. Measure openings after glue-up, then build boxes.",
        hiddenWork: "Stopped dados hide on the finished sides.",
      },
      {
        id: "dovetail",
        name: "Dovetailed drawers, web frames",
        recommendedRank: "craftsman",
        summary: "The furniture-maker's console. Web frames instead of a full dust bottom. Half-blind dovetails at the fronts.",
        joinery: "Half-blind dovetails, web frames, mortised legs.",
        tools: ["Dovetail saw", "chisels", "plow plane or router"],
        tradeoffs: "Slow. Beautiful. Walnut will show every layout mistake.",
        hiddenWork: "Web frames and drawer runners are the unseen structure.",
      },
    ],
    parts: [
      part({ id: "top", name: "Top", qty: 1, length: W(0.5), width: D(0.5), thickness: F(0.75), notes: "Slight overhang, ~¼\" per side." }),
      part({ id: "side", name: "Side", qty: 2, length: H(-6.5), width: D(-0.25), thickness: F(0.75), notes: "Carcase sits on a 4½\" leg reveal plus hangers." }),
      part({ id: "bottom", name: "Bottom / web", qty: 1, length: W(-1.5), width: D(-0.25), thickness: F(0.75) }),
      part({ id: "divider", name: "Center divider", qty: 1, length: H(-13), width: D(-0.5), thickness: F(0.75) }),
      part({ id: "back", name: "Back", qty: 1, length: W(-0.25), width: H(-7), thickness: F(0.25), stock: "plywood", notes: "¼\" plywood in a rabbet." }),
      part({ id: "leg", name: "Tapered leg", qty: 4, length: F(6), width: F(1.5), thickness: F(1.5), notes: "Taper inside faces; top 3\" stays full." }),
      part({ id: "dfront", name: "Drawer false front", qty: 2, length: W(-2.2), width: F(6), thickness: F(0.75) }),
      part({ id: "dside", name: "Drawer side", qty: 4, length: D(-2.5), width: F(5), thickness: F(0.5), stock: "hardwood-ply" }),
      part({ id: "dfront-box", name: "Drawer box front/back", qty: 4, length: W(-4.5), width: F(5), thickness: F(0.5), stock: "hardwood-ply" }),
      part({ id: "dbottom", name: "Drawer bottom", qty: 2, length: W(-4.75), width: D(-3), thickness: F(0.25), stock: "plywood" }),
    ],
    hardware: consoleHardware,
    steps: consoleSteps,
  },
  {
    id: "bookcase",
    name: "White oak bookcase",
    category: "bookcase",
    blurb: "Two sides, four shelves, a back that squares the case.",
    image: "/catalog/bookcase.jpg",
    overall: { w: 32, d: 12, h: 60 },
    thickness: 0.75,
    defaultSpecies: "white-oak",
    defaultRoute: "dado",
    indoor: true,
    interpretation:
      "Upright case with four shelves, through-sides, likely a thin back. Shelf joinery isn't visible from the front — dados are the structural choice, pins or pocket screws are the faster ones.",
    confidence: 0.84,
    uncertainties: [
      "Shelf count confirmed; attachment method is not.",
      "Back assumed ¼\" plywood.",
      "Toe-kick height assumed 3\".",
    ],
    routes: [
      {
        id: "pocket",
        name: "Pocket-screw shelves",
        recommendedRank: "beginner",
        summary: "Screws through the sides into shelf ends, plugged or on the inside. A Saturday bookcase.",
        joinery: "Pocket or confirmed screws + glue. Nailed back.",
        tools: ["Saw", "drill", "Kreg jig", "square"],
        tradeoffs: "Shelves aren't as stiff as dados. Keep span under 32\" or add a center divider.",
        hiddenWork: "Plugged screw holes on the sides, or accept inside pockets.",
      },
      {
        id: "dado",
        name: "Dadoed shelves",
        recommendedRank: "novice",
        summary: "The correct carcase joint. Shelves can't sag out of a dado the way they can out of screws.",
        joinery: "¼\"-deep dados, glue, back in a rabbet.",
        tools: ["Table saw or router", "dado set or jig"],
        tradeoffs: "You commit to shelf spacing now. Layout once, cut twice.",
        hiddenWork: "Through dados show on the sides unless you stop them or face-frame.",
      },
      {
        id: "adjustable",
        name: "Adjustable pins + fixed top and bottom",
        recommendedRank: "apprentice",
        summary: "Top, bottom, and one middle shelf dadoed. The rest on pins so the case can change.",
        joinery: "Dados for structure, ¼\" shelf pins for the rest.",
        tools: ["Shelf-pin jig", "router or table saw"],
        tradeoffs: "Pins look less 'built-in'. Much more useful.",
        hiddenWork: "A jig keeps the pin rows in line. That's the whole trick.",
      },
    ],
    parts: [
      part({ id: "side", name: "Side", qty: 2, length: H(0), width: D(0), thickness: F(0.75) }),
      part({ id: "top", name: "Top", qty: 1, length: W(0), width: D(0), thickness: F(0.75), notes: "Flush or ¼\" overhang — your call." }),
      part({ id: "shelf", name: "Shelf", qty: 4, length: W(-1.5), width: D(-0.25), thickness: F(0.75), notes: "If dadoed ¼\" deep, length becomes overallW − 1\"." }),
      part({ id: "kick", name: "Toe-kick", qty: 1, length: W(-1.5), width: F(3.5), thickness: F(0.75) }),
      part({ id: "back", name: "Back", qty: 1, length: W(-0.125), width: H(-0.125), thickness: F(0.25), stock: "plywood" }),
    ],
    hardware: [
      { id: "glue-b", name: "Wood glue", qty: 1, spec: "Titebond II, 16 oz", aisle: "Adhesives" },
      { id: "screws-b", name: "Pocket-hole screws", qty: 32, spec: "1¼\" coarse for plywood, fine for oak", aisle: "Kreg", forRoutes: ["pocket"] },
      { id: "pins", name: "Shelf pins", qty: 20, spec: "¼\" nickel or brass", aisle: "Cabinet hardware", forRoutes: ["adjustable"] },
      { id: "brads-b", name: "Brad nails", qty: 1, spec: "18 ga × ¾\"", aisle: "Fasteners" },
    ],
    steps: [
      {
        id: "k1",
        title: "Cut the sides and layout shelves",
        body: "Gang the two sides and mark shelf locations together so they can't disagree. Typical spacing is 12–14\" in the clear. Leave a 3\" kick.",
        techniques: ["square-cut"],
      },
      {
        id: "k2p",
        title: "Pocket-screw the shelves",
        body: "Two or three screws per shelf end. Glue the end grain. Check racking before the back goes on — the back is what locks it.",
        techniques: ["pocket-hole", "clamp-up"],
        forRoutes: ["pocket"],
      },
      {
        id: "k2d",
        title: "Cut dados",
        body: "¼\" deep, width matched to actual shelf thickness. A plywood shelf in a ¾\" dado is a sloppy joint. Sneak up.",
        techniques: ["dado"],
        forRoutes: ["dado", "adjustable"],
      },
      {
        id: "k3",
        title: "Rabbet and attach the back",
        body: "A ⅜ × ¼ rabbet around the back. Glue and nail the plywood in. Measure diagonals as you nail — this is the square.",
        techniques: ["clamp-up"],
      },
      {
        id: "k4",
        title: "Edge-band or face-frame, then finish",
        body: "Plywood edges get banding. Solid oak can take a small chamfer and oil, or stain if you want Mission.",
        techniques: ["edge-banding", "finish-oil"],
      },
    ],
  },
  {
    id: "coffee-table",
    name: "Walnut coffee table",
    category: "table",
    blurb: "A floating top on a four-leg apron base. Same grammar as the bench, different proportions.",
    image: "/catalog/coffee-table.jpg",
    overall: { w: 48, d: 24, h: 17 },
    thickness: 0.75,
    defaultSpecies: "walnut",
    defaultRoute: "pocket",
    indoor: true,
    interpretation:
      "Rectangular coffee table, solid or glue-up top, four square legs, shallow aprons. Construction is the bench's older sibling. The top must float.",
    confidence: 0.88,
    uncertainties: [
      "Top may be a veneered panel in the original — we spec a solid glue-up.",
      "Leg thickness assumed 1¾\" for visual weight at this width.",
    ],
    routes: [
      {
        id: "pocket",
        name: "Pocket-hole apron",
        recommendedRank: "beginner",
        summary: "Same method as the bench. Figure-8 the top. Done in a weekend.",
        joinery: "Pocket holes + glue. Floating top.",
        tools: ["Kreg jig", "saw", "drill", "clamps"],
        tradeoffs: "Inside of aprons show screws. Nobody looks there.",
        hiddenWork: "Underside pocket holes and figure-8s.",
      },
      {
        id: "mortise",
        name: "Mortise and tenon, floating top",
        recommendedRank: "craftsman",
        summary: "Haunched tenons, maybe a drawbore if you want to show off. This is the piece that teaches movement.",
        joinery: "Haunched M&T, figure-8 or buttons for the top.",
        tools: ["Mortiser", "tenon saw", "plane"],
        tradeoffs: "A 24\"-deep top moves. Design for it or it cups against the aprons.",
        hiddenWork: "Buttons or figure-8s in the apron.",
      },
    ],
    parts: [
      part({ id: "top", name: "Top", qty: 1, length: W(0), width: D(0), thickness: F(0.75), notes: "Glue-up. Grain runs the 48\" direction." }),
      part({ id: "leg", name: "Leg", qty: 4, length: H(-0.75), width: F(1.75), thickness: F(1.75) }),
      part({ id: "apron-l", name: "Long apron", qty: 2, length: W(-3.5), width: F(3.5), thickness: F(0.75) }),
      part({ id: "apron-s", name: "Short apron", qty: 2, length: D(-3.5), width: F(3.5), thickness: F(0.75) }),
    ],
    hardware: [
      { id: "kreg-t", name: "Pocket-hole screws", qty: 24, spec: "1¼\" fine-thread #8", aisle: "Kreg", forRoutes: ["pocket"] },
      { id: "fig8-t", name: "Figure-8 fasteners", qty: 8, spec: "With #6 × ⅝\" screws", aisle: "Tabletop hardware" },
      { id: "glue-t", name: "Wood glue", qty: 1, spec: "Titebond II, 8 oz", aisle: "Adhesives" },
    ],
    steps: [
      {
        id: "t1",
        title: "Glue up the top",
        body: "Match figure across the joint. Alternate cups. Cauls. This top is the whole piece — spend the time.",
        techniques: ["glue-up"],
      },
      {
        id: "t2",
        title: "Build the base square",
        body: "Identical leg lengths. Aprons between them. Diagonals. A coffee table that rocks is a coffee table you will hate.",
        techniques: ["square-cut", "clamp-up", "pocket-hole"],
        forRoutes: ["pocket"],
      },
      {
        id: "t2m",
        title: "Mortise and tenon the base",
        body: "Same as the bench, with more visual weight in the legs. Drawbore if you like a mechanical lock.",
        techniques: ["mortise-tenon", "clamp-up"],
        forRoutes: ["mortise"],
      },
      {
        id: "t3",
        title: "Float the top, oil the walnut",
        body: "Figure-8s. No glue on the top. Oil, wipe, repeat. Don't stain walnut.",
        techniques: ["wood-movement", "finish-oil"],
      },
    ],
  },
  {
    id: "cabinet",
    name: "Shaker wall cabinet",
    category: "cabinet",
    blurb: "A single inset door, one shelf, hanging cleat. Paint-grade or show wood.",
    image: "/catalog/cabinet.jpg",
    overall: { w: 24, d: 12, h: 30 },
    thickness: 0.75,
    defaultSpecies: "poplar",
    defaultRoute: "dado",
    indoor: true,
    interpretation:
      "Wall-hung Shaker cabinet, single inset door, likely one adjustable or fixed shelf, hanging method not visible. Door joinery (frame-and-panel vs. slab) is a route.",
    confidence: 0.8,
    uncertainties: [
      "Hanging cleat vs. French cleat is not visible.",
      "Door is inset — hinges could be butt, partial wrap, or knife.",
      "Interior shelf count inferred as one.",
    ],
    routes: [
      {
        id: "dado",
        name: "Dadoed box, slab door",
        recommendedRank: "novice",
        summary: "Plywood or solid box with dados. A slab door on overlay or inset hinges. Paint it.",
        joinery: "Dados + glue, rabbeted back, slab door.",
        tools: ["Saw", "router or table saw", "hinge jig"],
        tradeoffs: "A slab door will move if it's solid wood wider than 10\". Use ply for the door if you paint.",
        hiddenWork: "French cleat on the back.",
      },
      {
        id: "frame",
        name: "Frame-and-panel door, mortised box",
        recommendedRank: "craftsman",
        summary: "The Shaker object. Mortise-and-tenon door, floating panel, inset on brass butts or knife hinges.",
        joinery: "M&T door, dados or M&T carcase, inset.",
        tools: ["Mortiser", "plow or router", "hinges", "plane"],
        tradeoffs: "Inset work is about even reveals. Take a day for the door alone.",
        hiddenWork: "Floating panel, French cleat, hinge mortises.",
      },
    ],
    parts: [
      part({ id: "side", name: "Side", qty: 2, length: H(0), width: D(0), thickness: F(0.75) }),
      part({ id: "tb", name: "Top / bottom", qty: 2, length: W(-1.5), width: D(0), thickness: F(0.75) }),
      part({ id: "shelf", name: "Shelf", qty: 1, length: W(-1.5), width: D(-0.25), thickness: F(0.75) }),
      part({ id: "back", name: "Back", qty: 1, length: W(-0.125), width: H(-0.125), thickness: F(0.25), stock: "plywood" }),
      part({ id: "cleat", name: "French cleat", qty: 2, length: W(-1.5), width: F(3.5), thickness: F(0.75), notes: "Bevel 45°. One on cabinet, one on wall." }),
      part({ id: "door", name: "Door slab or panel", qty: 1, length: H(-0.125), width: W(-0.125), thickness: F(0.75), notes: "Inset: leave 1/16 reveal each side after hinging." }),
      part({ id: "stiles", name: "Door stiles (frame route)", qty: 2, length: H(-0.125), width: F(2), thickness: F(0.75), notes: "Used on the frame-and-panel route." }),
      part({ id: "rails", name: "Door rails (frame route)", qty: 2, length: W(-4.125), width: F(2), thickness: F(0.75) }),
    ],
    hardware: [
      { id: "hinges", name: "Inset hinges", qty: 2, spec: "Brass butt 2\" or partial-wrap cabinet hinges", aisle: "Cabinet hardware" },
      { id: "knob", name: "Knob", qty: 1, spec: "¾–1\" wood or brass", aisle: "Cabinet hardware" },
      { id: "glue-w", name: "Wood glue", qty: 1, spec: "Titebond II, 8 oz", aisle: "Adhesives" },
      { id: "catch", name: "Magnetic catch", qty: 1, spec: "Optional, if the hinge isn't self-closing", aisle: "Cabinet hardware" },
    ],
    steps: [
      {
        id: "w1",
        title: "Build a square box",
        body: "Dados or rabbets. Back in a rabbet. Diagonals. A wall cabinet that isn't square makes an inset door look drunk.",
        techniques: ["dado", "clamp-up"],
      },
      {
        id: "w2",
        title: "Hang it on a French cleat",
        body: "Two 45° cleats, long point of the bevel up on the wall, down on the cabinet. Hit studs. A 30×24 cabinet full of dishes is not a drywall-anchor project.",
        techniques: ["square-cut"],
      },
      {
        id: "w3",
        title: "Fit the door",
        body: "Plane to a 1/16\" reveal. Mortise hinges. A slab door in poplar, painted, is the beginner win. Frame-and-panel if you want it to stay flat in solid wood.",
        techniques: ["finish-paint"],
        forRoutes: ["dado"],
      },
      {
        id: "w3f",
        title: "Frame-and-panel door",
        body: "Mortise the stiles, tenon the rails, panel floats in a groove. Don't glue the panel. That's the movement lesson in miniature.",
        techniques: ["mortise-tenon", "wood-movement"],
        forRoutes: ["frame"],
      },
    ],
  },
  {
    id: "adirondack",
    name: "Adirondack chair",
    category: "chair",
    blurb: "Westport-style. Wide arms, fan back, a seat you can live in all afternoon.",
    image: "/catalog/adirondack.jpg",
    overall: { w: 30, d: 36, h: 38 },
    thickness: 0.75,
    defaultSpecies: "cedar",
    defaultRoute: "screwed",
    indoor: false,
    interpretation:
      "Classic Westport Adirondack: fan back, wide flat arms that meet the back legs, deep reclined seat. Built from 1× slats on shaped sides. Outdoor joinery is mechanical — screws and bolts, not glue as the primary structure.",
    confidence: 0.86,
    uncertainties: [
      "Exact back-slat count varies (commonly 7). We spec 7.",
      "Seat angle is the whole comfort. A template is safer than inventing it.",
      "Original may be cypress, cedar, or poly lumber — pick a weather wood.",
    ],
    routes: [
      {
        id: "screwed",
        name: "Stainless screws, cedar",
        recommendedRank: "beginner",
        summary: "The honest outdoor chair. Predrill, stainless, a little glue on the arms. Sit in it the same weekend.",
        joinery: "Stainless deck screws, predrilled. Glue is a helper, not the structure.",
        tools: ["Jigsaw or bandsaw", "drill", "sander", "clamps"],
        tradeoffs: "Screw heads show. That's correct on this piece. Plug them if you want.",
        hiddenWork: "Seat-side profile is the hidden pattern — print a template.",
      },
      {
        id: "plugged",
        name: "Plugged screws, shaped arms",
        recommendedRank: "apprentice",
        summary: "Same chair, slower. Counterbore and plug every show screw. Fair the arms with a plane.",
        joinery: "Counterbored stainless, cedar plugs, spar or oil finish.",
        tools: ["Jigsaw", "plug cutter", "plane", "drill"],
        tradeoffs: "A lot of plugs. Looks like furniture instead of deck-building.",
        hiddenWork: "Grain-matched plugs on the arms.",
      },
    ],
    parts: [
      part({ id: "side", name: "Seat side (pattern)", qty: 2, length: D(-2), width: F(7.25), thickness: F(0.75), notes: "Cut from 1×8. This is the comfort template." }),
      part({ id: "front-leg", name: "Front leg", qty: 2, length: F(20), width: F(3.5), thickness: F(0.75) }),
      part({ id: "back-leg", name: "Back leg / riser", qty: 2, length: F(32), width: F(5.5), thickness: F(0.75) }),
      part({ id: "arm", name: "Arm", qty: 2, length: F(28), width: F(5.5), thickness: F(0.75) }),
      part({ id: "back-slat", name: "Back slat", qty: 7, length: F(32), width: F(3.5), thickness: F(0.75), notes: "Fan: longer in the middle if you taper the tops." }),
      part({ id: "seat-slat", name: "Seat slat", qty: 6, length: W(-2), width: F(2.5), thickness: F(0.75), notes: "Gap ⅜\" for drainage." }),
      part({ id: "stretcher", name: "Front stretcher", qty: 1, length: W(-2), width: F(3.5), thickness: F(0.75) }),
      part({ id: "brace", name: "Arm brace", qty: 2, length: F(8), width: F(3.5), thickness: F(0.75) }),
    ],
    hardware: [
      { id: "ss-screws", name: "Stainless deck screws", qty: 1, spec: "Box of #8 × 1¾\" and #8 × 1¼\"", aisle: "Fasteners / exterior" },
      { id: "bolts", name: "Carriage bolts", qty: 4, spec: "¼-20 × 2½\" stainless, with washers and nuts", aisle: "Fasteners" },
      { id: "glue-a", name: "Waterproof glue", qty: 1, spec: "Titebond III, 8 oz", aisle: "Adhesives" },
      { id: "finish-a", name: "Penetrating oil", qty: 1, spec: "Exterior oil, 1 pint", aisle: "Finishes" },
    ],
    steps: [
      {
        id: "a1",
        title: "Make the side-pattern first",
        body: "The seat-side profile is the chair. Use a paper template, cut one, fair it, then trace the second. Don't invent this freehand on expensive cedar.",
        techniques: ["square-cut"],
      },
      {
        id: "a2",
        title: "Assemble the sides, then the stretchers",
        body: "Predrill every stainless screw. Cedar splits on command. Bolt the front legs if you want a chair that loosens and retightens after a season.",
        techniques: ["clamp-up"],
      },
      {
        id: "a3",
        title: "Seat slats, then the fan back",
        body: "Gap the slats. Start the back from the center slat and work out so the fan is even. Ease every edge — this is a chair you touch.",
        techniques: ["square-cut"],
      },
      {
        id: "a4",
        title: "Arms, then outdoor finish",
        body: "Arms make the chair. They should land level and proud of the back. Oil, don't film-finish, unless you like scraping spar urethane in two years.",
        techniques: ["outdoor-finish"],
      },
    ],
  },
];

export function getTemplate(id: string): ProjectTemplate | undefined {
  return CATALOG.find((p) => p.id === id);
}

export function matchTemplate(
  category: string | undefined,
  name: string | undefined,
): ProjectTemplate | undefined {
  const blob = `${category ?? ""} ${name ?? ""}`.toLowerCase();
  const hits: [string, string][] = [
    ["bench", "bench"],
    ["console", "console"],
    ["console", "credenza"],
    ["console", "sideboard"],
    ["console", "nightstand"],
    ["console", "media"],
    ["bookcase", "bookcase"],
    ["bookcase", "bookshelf"],
    ["bookcase", "shelves"],
    ["coffee-table", "coffee"],
    ["cabinet", "cabinet"],
    ["cabinet", "cupboard"],
    ["adirondack", "adirondack"],
    ["adirondack", "chair"],
  ];
  for (const [id, needle] of hits) {
    if (blob.includes(needle)) return getTemplate(id);
  }
  return undefined;
}
