import type { Species } from "./types";

export const SPECIES: Species[] = [
  {
    id: "maple",
    name: "Hard maple",
    density: 44,
    janka: 1450,
    cost: "$$",
    indoor: "Tight grain, takes a beating. Classic for benches and tabletops.",
    stain: "Blotches with oil stain unless you pre-condition. Looks best clear or with dye.",
    weather: "Not a weather wood. Keep it indoors.",
    movement: "Moderate. Glue up tops with the grain matched; don't pin a breadboard tightly.",
    notes: "Heavy. A 48×14×¾ maple top is already ~18 lb before aprons.",
    outdoorOk: false,
    typicalStock: "1× and 5/4 S4S at hardwood dealers; limited at big-box.",
  },
  {
    id: "walnut",
    name: "Black walnut",
    density: 38,
    janka: 1010,
    cost: "$$$$",
    indoor: "The furniture wood. Rich brown, machines cleanly, finishes with oil alone.",
    stain: "Skip stain. Rub on oil or wiping varnish and stop.",
    weather: "Will silver and check outdoors. Indoor only unless fully encapsulated.",
    movement: "Better than oak. Still needs a floating top on a table base.",
    notes: "Price swings. Buy on a weekday at a hardwood dealer, not big-box 'walnut-look' plywood.",
    outdoorOk: false,
    typicalStock: "4/4 and 5/4 at DFW hardwood yards; rarely at Home Depot.",
  },
  {
    id: "white-oak",
    name: "White oak",
    density: 47,
    janka: 1360,
    cost: "$$$",
    indoor: "Strong, with ray fleck if quarter-sawn. Traditional casework wood.",
    stain: "Takes stain evenly. Mission brown and fumed looks are classic.",
    weather: "The outdoor oak. High tannin, closed pores. Still finish it.",
    movement: "Moves more than walnut. Frame-and-panel or breadboard on wide tops.",
    notes: "Tannins react with steel fasteners — use stainless or brass outdoors.",
    outdoorOk: true,
    typicalStock: "4/4, 5/4, 8/4 at hardwood dealers; red oak is the big-box stand-in.",
  },
  {
    id: "red-oak",
    name: "Red oak",
    density: 44,
    janka: 1290,
    cost: "$$",
    indoor: "Open grain, strong, easy to find. Reads as 'oak furniture' immediately.",
    stain: "Drinks stain. Fill the pores if you want a smooth film finish.",
    weather: "Worse than white oak outdoors. Indoor unless you're building a rustic piece you'll refinish.",
    movement: "Active. Don't glue a wide top down to aprons.",
    notes: "Cheapest 'real hardwood' at big-box. Quality is hit-or-miss — pick boards yourself.",
    outdoorOk: false,
    typicalStock: "1×3 through 1×12 at Home Depot / Lowe's.",
  },
  {
    id: "pine",
    name: "Southern yellow pine",
    density: 41,
    janka: 870,
    cost: "$",
    indoor: "Cheap, stiff, dents easily. Fine for shop furniture and painted work.",
    stain: "Blotchy. Paint, milk paint, or a gel stain. Don't chase a furniture look.",
    weather: "Use pressure-treated or cedar outdoors instead. SYP checks hard in Texas sun.",
    movement: "Wild if you buy wet construction lumber. Let it dry in the shop a week.",
    notes: "A 2×8 from the rack is not 7¼ × 1½. Measure. And watch for bow.",
    outdoorOk: false,
    typicalStock: "Dimensional 2× and 1× everywhere. Pick straight, skip the wet packs.",
  },
  {
    id: "cedar",
    name: "Western red cedar",
    density: 23,
    janka: 350,
    cost: "$$",
    indoor: "Too soft for a dining table. Perfect for outdoor seating and linings.",
    stain: "Skip heavy stain. Oil or a penetrating deck finish. It wants to breathe.",
    weather: "The default Adirondack wood. Light, rot-resistant, silvers if left raw.",
    movement: "Stable for a softwood. Still gap seat slats for drainage.",
    notes: "Dust is an irritant — mask up. Stainless fasteners only.",
    outdoorOk: true,
    typicalStock: "1×4, 1×6, 5/4 decking at big-box; clearer stock at lumberyards.",
  },
  {
    id: "plywood-oak",
    name: "Oak plywood (¾\")",
    density: 33,
    janka: 1290,
    cost: "$$",
    indoor: "Stable carcases. Use solid-wood edge banding or face frames so edges don't read as ply.",
    stain: "Veneer stains faster than solid. Test on a cutoff. Color-match the banding.",
    weather: "Interior grade delaminates outside. Don't.",
    movement: "Almost none across the sheet. That's the point.",
    notes: "A 4×8 of ¾ cabinet-grade in Dallas runs ~$70–110. Baltic birch is nicer for drawers.",
    outdoorOk: false,
    typicalStock: "4×8 sheets at big-box and hardwood dealers (better veneer at dealers).",
  },
  {
    id: "poplar",
    name: "Poplar",
    density: 29,
    janka: 540,
    cost: "$",
    indoor: "The paint-grade hardwood. Green streaks vanish under paint or dye.",
    stain: "Goes muddy. Paint it, or dye it dark. Not a clear-finish wood.",
    weather: "No. Soft and not rot-resistant.",
    movement: "Moderate. Fine for painted casework and interior trim.",
    notes: "Best value for a beginner carcase you'll paint. Machines like butter.",
    outdoorOk: false,
    typicalStock: "1× at big-box; 4/4 S4S at hardwood dealers, often cheapest bin.",
  },
];

export function getSpecies(id: string): Species {
  return SPECIES.find((s) => s.id === id) ?? SPECIES[0]!;
}
