import { dim } from "../parametric";
import type { ProjectTemplate } from "../types";

const { W, D, H, F } = dim;

export const feederTemplate: ProjectTemplate = {
  id: "feeder",
  name: "Cedar hopper feeder",
  category: "feeder",
  blurb:
    "Hip-roof lift-off hat, PETG hopper in grooved posts, tray on a 1\" pole. Shop-plan complete.",
  image: "/catalog/feeder.svg",
  overall: { w: 14.5, d: 14.5, h: 18 },
  thickness: 0.75,
  defaultSpecies: "cedar",
  defaultRoute: "screwed",
  indoor: false,
  interpretation:
    "Improved replica of a hip-roof hopper feeder. Four ⅛\" PETG panels slide in grooved 1×1 posts. The roof is a lift-off hat: plywood pyramid, clapboard slats ~5/16\", copper on the hips. Tray is 13½\" square on a 1\" NPT floor flange. Not terracotta — the hopper is plastic.",
  confidence: 0.96,
  uncertainties: [
    "The original scan's 'yellow hopper' was dirty acrylic, not wood and not terracotta.",
    "Slat thickness is a resaw of ¾\" — about 5/16\", not a true ⅜\".",
    "Ogee on the apron is optional. Square-bottom is fine.",
  ],
  stack: [
    "Posts 1×1 × 7½\" (glued 1-by)",
    "Apron ¾×2½×10\" long-point",
    "Post outer envelope 8½\"",
    "Opening between posts 6½\"",
    "PETG 7\" × 7\"",
    "Soffit 12×12 sits on the apron",
    "Plug 6⅝\" × ¾\" drops into 6½\"",
    "Roof eave 14½\" · tray 13½\"",
  ],
  routes: [
    {
      id: "screwed",
      name: "Stainless, lift-off roof",
      recommendedRank: "novice",
      summary:
        "The plan as written. Grooved posts, PETG from the top, roof is a hat located by the plug. No dowels.",
      joinery:
        "Glue + #8 stainless. ¼×¼ grooves in the posts. Hip cleats inside the plywood pyramid. Nails on slats.",
      tools: [
        "Table saw",
        "miter saw",
        "drill",
        "tall resaw fence",
        "square",
      ],
      tradeoffs:
        "Screws show on the apron. That's correct. Wind lock is the plug, not a deep skirt.",
      hiddenWork:
        "¼×¼ grooves and a ½\" inner roundover on two faces of each post. Hip cleats you never see.",
    },
    {
      id: "plugged",
      name: "Plugged screws, square apron",
      recommendedRank: "apprentice",
      summary:
        "Same feeder, slower. Skip the ogee. Counterbore and plug every show screw on the apron.",
      joinery: "Same grooves and hip cleats. Plugged #8s on the apron band.",
      tools: ["Table saw", "plug cutter", "drill", "plane"],
      tradeoffs: "A lot of tiny cedar plugs. Looks like furniture instead of a kit.",
      hiddenWork: "Grain-matched plugs on the apron.",
    },
  ],
  parts: [
    {
      id: "tray",
      letter: "A",
      name: "Tray floor",
      qty: 1,
      length: W(-1),
      width: D(-1),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 1 (glue two 6¾\" rips)",
      notes: "Crosscut 14\". Rip two 6¾\" strips. Glue. Square after it dries. 13½\" × 13½\".",
    },
    {
      id: "rim-l",
      letter: "B",
      name: "Tray rim long",
      qty: 2,
      length: W(-1),
      width: F(1.5),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 6, on edge",
      notes: "1½\" × 13½\". On edge around the tray.",
    },
    {
      id: "rim-s",
      letter: "C",
      name: "Tray rim short",
      qty: 2,
      length: F(12),
      width: F(1.5),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 6, on edge",
      notes: "1½\" × 12\". Fits between the long rims.",
    },
    {
      id: "post",
      letter: "F",
      name: "Corner posts",
      qty: 4,
      length: H(-10.5),
      width: F(1),
      thickness: F(1),
      stock: "solid",
      grain: "length",
      fromStock: "Board 1 leftover, glued + milled",
      notes:
        "Glue two ¾×1¼×8\" in pairs. Mill to 1×1 × 7½\". Glue line OUT. ¼×¼ groove on two inner faces. ½\" inner roundover.",
    },
    {
      id: "apron",
      letter: "G",
      name: "Apron",
      qty: 4,
      length: F(10),
      width: F(2.5),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 5, 45° miters",
      notes:
        "10\" long-point, 8½\" short-point. Miters first, curve last — or skip the curve. Two #8 × 1¼\" per side into the post.",
    },
    {
      id: "roof-tri",
      letter: "H",
      name: "Roof triangle",
      qty: 4,
      length: F(12),
      width: W(0),
      thickness: F(0.5),
      stock: "plywood",
      grain: "length",
      fromStock: "24×48 × ½\" plywood (not 24×24)",
      notes: "14½\" base, 12\" slant height, apex ~62°. No bevel. Edges butt at the hips.",
    },
    {
      id: "soffit",
      letter: "N",
      name: "Soffit plate",
      qty: 1,
      length: F(12),
      width: F(12),
      thickness: F(0.5),
      stock: "plywood",
      grain: "length",
      fromStock: "same 24×48 sheet",
      notes: "Sits on the apron. #8 × 1\" from UNDER into each triangle, 2 per side.",
    },
    {
      id: "cleat",
      letter: "R",
      name: "Hip cleat (inside)",
      qty: 4,
      length: F(9),
      width: F(0.75),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 7",
      notes:
        "Lives inside the hip. The two plywood faces butt — they do not cross. Four #6 × 1\" per cleat.",
    },
    {
      id: "plug",
      letter: "Q",
      name: "Roof plug",
      qty: 1,
      length: F(6.625),
      width: F(6.625),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 1 leftover",
      notes: "6⅝\" square. Drops into the 6½\" opening. Locates the hat. Wind lock.",
    },
    {
      id: "slat",
      letter: "J",
      name: "Roof slats",
      qty: 36,
      length: F(16),
      width: F(1.75),
      thickness: F(0.3125),
      stock: "solid",
      grain: "length",
      fromStock: "Board 2, rip then resaw",
      notes:
        "16\" blanks. Hang long, nail high, trim. ~5/16\" thick — a resaw of ¾\", not a true ⅜\".",
    },
    {
      id: "hipcap",
      letter: "K",
      name: "Hip caps",
      qty: 8,
      length: F(15),
      width: F(1.75),
      thickness: F(0.3125),
      stock: "solid",
      grain: "length",
      fromStock: "leftover slats, 2 per hip",
      notes: "Copper first, then one slat on each side of the hip.",
    },
    {
      id: "peak",
      letter: "L",
      name: "Peak cap",
      qty: 1,
      length: F(3),
      width: F(3),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "Board 1 leftover",
      notes: "3×3 cedar square on top of the four cap ends.",
    },
    {
      id: "hopper",
      letter: "P",
      name: "Hopper panel",
      qty: 4,
      length: F(7),
      width: F(7),
      thickness: F(0.125),
      stock: "sheet",
      grain: "length",
      fromStock: "PETG ⅛\" (not acrylic)",
      notes:
        "7×7. ¼\" radius notches at two corners. Slide in from the top. Groove-test a strip first.",
    },
  ],
  hardware: [
    {
      id: "screws-15",
      name: "#8 × 1½\" stainless wood screws",
      qty: 12,
      spec: "Box of #8 × 1½\" stainless",
      aisle: "Fasteners / stainless",
      where:
        "8 rims B/C → tray A · 4 posts F → tray A (one per post, from inside)",
    },
    {
      id: "screws-125",
      name: "#8 × 1¼\" stainless wood screws",
      qty: 8,
      spec: "Box of #8 × 1¼\" stainless",
      aisle: "Fasteners / stainless",
      where:
        "8 apron G → posts F (2 per side, through the solid band, predrill)",
    },
    {
      id: "screws-1-peak",
      name: "#8 × 1\" stainless wood screws",
      qty: 4,
      spec: "Box of #8 × 1\" stainless",
      aisle: "Fasteners / stainless",
      where: "4 peak cap L → hip caps / plywood",
    },
    {
      id: "screws-1-soffit",
      name: "#8 × 1\" stainless wood screws",
      qty: 8,
      spec: "Same #8 × 1\" box",
      aisle: "Fasteners / stainless",
      where: "8 soffit N → triangles H (2 per side, from UNDER the soffit)",
    },
    {
      id: "screws-6",
      name: "#6 × 1\" stainless wood screws",
      qty: 16,
      spec: "#6 × 1\" stainless",
      aisle: "Fasteners / stainless",
      where:
        "4 per hip cleat R — 2 into each triangle. These hold the pyramid together.",
    },
    {
      id: "nails",
      name: "4d (1½\") stainless or copper nails",
      qty: 90,
      spec: "4d stainless or copper, ~90",
      aisle: "Fasteners",
      where:
        "2 per slat J (~72) · 2 per hip cap K (16). Nail HIGH so the next slat covers them.",
    },
    {
      id: "bolts",
      name: "¼-20 × 1½\" SS carriage bolts + nuts + washers",
      qty: 4,
      spec: "¼-20 × 1½\" stainless, 4 ea with nuts and washers",
      aisle: "Fasteners",
      where: "Floor flange → tray A",
    },
    {
      id: "flange",
      name: "1\" galvanized floor flange (NPT)",
      qty: 1,
      spec: "1\" galvanized, plumbing aisle",
      aisle: "Plumbing",
      where: "Underside of tray. 1\" pipe / pole below.",
    },
    {
      id: "glue",
      name: "Titebond III",
      qty: 1,
      spec: "8 oz, waterproof",
      aisle: "Adhesives",
      where: "Post glue-ups, tray, apron miters, hip edges, soffit, plug",
    },
    {
      id: "copper",
      name: "Copper roll flashing 8\"×20'",
      qty: 1,
      spec: "Union Corrugating or equivalent. ~5 ft used.",
      aisle: "Roofing / Lowe's",
      where: "Hips, after slats are trimmed, before wooden caps",
    },
    {
      id: "oil",
      name: "Penetrating cedar oil",
      qty: 1,
      spec: "Penofin or similar, pint",
      aisle: "Finishes",
      where: "Every cedar face. Not PETG.",
    },
  ],
  steps: [
    {
      id: "f1",
      title: "Cut Board 1 — tray, plug, peak, post blanks",
      body: "Pick the flattest 1×12. Crosscut 14\". Rip two 6¾\" strips and glue them into A, 13½\" square. Square it after it dries. From leftover: Q plug 6⅝\" square, L peak 3×3. Rip a 1¼\" strip, cut eight ¾×1¼×8\", glue in pairs, mill to F 1×1 × 7½\".",
      techniques: ["glue-up", "square-cut"],
    },
    {
      id: "f2",
      title: "Groove and round the posts",
      body: "Glue line on the OUTSIDE, away from the hopper. ¼×¼ groove on two inner faces. ½\" inner roundover. Groove-test a PETG strip before you commit all four posts. A1 print of the hopper is 178×178×3.0 mm if you're printing instead of cutting sheet.",
      techniques: ["square-cut"],
    },
    {
      id: "f3",
      title: "Tray, rims, drains, flange hole",
      body: "Glue + #8 × 1½\" rims B/C on edge, 2–3 screws per side, predrill. Drill a 1¼\" flange hole in A. Four ¼\" bolt holes. ¼\" drains at corners and mid-sides.",
      techniques: ["square-cut"],
    },
    {
      id: "f4",
      title: "Apron around the four posts",
      body: "Board 5, not Board 3. Rip 2½\" off the 3½\" face. Four aprons, 10\" long-point, 45° miters. Miters first, curve last — or skip the curve. Glue the miters. Two #8 × 1¼\" per side into the post, through the solid band, ~¾\" from each end. Dry-fit around the posts before glue.",
      techniques: ["square-cut", "clamp-up"],
      forRoutes: ["screwed"],
    },
    {
      id: "f4p",
      title: "Apron, plugged screws, skip the ogee",
      body: "Same 10\" long-point miters. Square bottom. Counterbore the two screws per side and plug with cedar. Glue the miters. Dry-fit first.",
      techniques: ["square-cut", "clamp-up"],
      forRoutes: ["plugged"],
    },
    {
      id: "f5",
      title: "Stand the box on the tray",
      body: "Center it. #8 × 1½\" — 1 per post, from inside the hopper down into the tray, or up through the tray into the post. Then bolt the flange: 4 carriage bolts.",
      techniques: ["clamp-up"],
    },
    {
      id: "f6",
      title: "Slide PETG from the top",
      body: "Four 7×7 panels, ¼\" radius notches at the grooved corners. They slide out the top for cleaning. Do not buy acrylic. Oil the cedar. Not the PETG.",
      techniques: ["square-cut"],
    },
    {
      id: "f7",
      title: "Roof triangles and the hip cleats",
      body: "Buy 24×48 × ½\" exterior plywood. Not 24×24 — four 14½\" triangles plus a 12×12 soffit will not fit. Lay the triangle with a square and a straightedge. No bevel. Tape the four into a pyramid, bases a 14½\" square, peaks touching. Edges butt. They do not cross. Nest a ¾×¾×9\" cleat in each hip valley. If it rocks, knock one corner off until it sits on both inner faces. Glue. Four #6 × 1\" per hip, staggered, two through each triangle into the cleat. Pull the outside tape. Pyramid is rigid.",
      techniques: ["hip-cleat", "clamp-up"],
    },
    {
      id: "f8",
      title: "Soffit from below, then the plug",
      body: "Drive #8 × 1\" through the soffit up into each triangle — 2 per side, eight total. Stay inboard of the 1¼\" overhang so you hit wood, not air. Predrill. The plug 6⅝\" drops into the 6½\" opening and locates the hat. Lift straight up to fill. No deep skirt.",
      techniques: ["square-cut"],
    },
    {
      id: "f9",
      title: "Resaw Board 2 into slats",
      body: "This is the only full-6' user. Board flat on the table, fence 1¾\", blade ~1\" high, rip six strips. Then resaw each strip ON EDGE against a tall fence — two passes that meet in the middle. Same face against the fence on both passes. ¾\" minus ~⅛\" kerf split in half is ~5/16\". That is the look. Do not stand the 1×12 on edge. Thin-kerf blade if you have one. Then crosscut 16\" blanks. Keep ~36 slats + 8 hip caps at 15\".",
      techniques: ["resaw"],
    },
    {
      id: "f10",
      title: "Hang slats long, trim, copper, caps",
      body: "They lap. They are not stacked end to end. Spacer: 1¾\" shows, 1¾ minus 1¼ = ½\" buried. First slat even with the plywood drip, or ¼\" past it. 16\" blanks centered, hanging past both hips. Two 4d nails, HIGH. Pull-saw both hips, plywood as the guide. Faces do not weave. Copper flashing folded over each hip, then one leftover slat on the LEFT of that hip and one on the RIGHT. Peak 3×3 last, four #8 × 1\" or four 4d nails. Trim flush on a straightedge clamped to the plywood hip. Do not undercut.",
      techniques: ["resaw", "outdoor-finish"],
    },
  ],
  buyBoards: [
    {
      id: "b1",
      label: "BOARD 1",
      stock: "1×12 × 6'",
      bdft: 6,
      role: "BEST / FLATTEST",
      yields: "A tray · Q plug · L peak · F post blanks",
      body: "Crosscut 14\". Rip two 6¾\" strips. Glue into A 13½\" × 13½\" tray. Square after it dries. From leftover: Q plug 6⅝\" × 6⅝\", L peak 3\" × 3\". Rip 1¼\" strip. Cut 8 pcs ¾\" × 1¼\" × 8\". Glue in pairs. Mill to F 1×1 × 7½\".",
    },
    {
      id: "b2",
      label: "BOARD 2",
      stock: "1×12 × 6'",
      bdft: 6,
      role: "NEXT-FLATTEST · RESAW",
      yields: "J ~36 slats · K 8 hip caps",
      body: "Keep this one a full 6'. Fence 1¾\", rip six strips. Resaw each down the middle. Crosscut 16\" blanks. You need ~36 slats + 8 hip caps at 15\". Extra blanks left over. See the resaw sheet.",
    },
    {
      id: "b3",
      label: "BOARD 3",
      stock: "1×12 × 6'",
      bdft: 6,
      role: "SPARE",
      yields: "Extra slats, extra posts, blown cuts",
      body: "Do not cut until Boards 1 and 2 are done.",
      spare: true,
    },
    {
      id: "b4",
      label: "BOARD 4",
      stock: "1×12 × 6'",
      bdft: 6,
      role: "SPARE",
      yields: "Park it",
      body: "Same. Park it.",
      spare: true,
    },
    {
      id: "b5",
      label: "BOARD 5",
      stock: "1×4 × 6'",
      bdft: 2,
      role: "APRON",
      yields: "G 4 aprons",
      body: "Rip 2½\" off the 3½\" face. Cut G, 4 aprons, 10\" long-point, 45° miters. Curve optional. Leftover 1\" strip is scrap. This is Board 5, not Board 3.",
    },
    {
      id: "b6",
      label: "BOARD 6",
      stock: "1×4 × 6'",
      bdft: 2,
      role: "TRAY RIMS",
      yields: "B 2 pcs 1½\" × 13½\" · C 2 pcs 1½\" × 12\"",
      body: "Rip 1½\" off the 3½\" face. On edge around the tray. Leftover is spare.",
    },
    {
      id: "b7",
      label: "BOARD 7",
      stock: "1×4 × 6'",
      bdft: 2,
      role: "HIP CLEATS",
      yields: "R four ¾\" × ¾\" × 9\"",
      body: "Rip ¾\" × ¾\", four at 9\". Rest is spare. Board 7 is the four hip cleats, not spare.",
    },
    {
      id: "b8",
      label: "BOARD 8",
      stock: "1×4 × 6'",
      bdft: 2,
      role: "SPARE",
      yields: "Park it",
      body: "Park it.",
      spare: true,
    },
  ],
  stillBuy: [
    "24×48 × ½\" exterior plywood (2×4 ft project panel). 24×24 is too small.",
    "PETG 12×24×⅛\" sheet, or print four 178×178×3.0 mm Bambu Translucent panels. Not acrylic.",
    "Every fastener on the Hardware tab.",
  ],
  doNotBuy: [
    "Cedar — you already have it",
    "Pickets",
    "1×8",
    "¼\" dowels",
    "24×24 plywood",
    "Acrylic / plexiglass — it cracks on the table saw",
  ],
};
