import { dim } from "../parametric";
import type { ProjectTemplate } from "../types";

const { W, D, H, F } = dim;

export const sideChairTemplate: ProjectTemplate = {
  id: "side-chair",
  name: "Lattice-back chair",
  category: "chair",
  blurb:
    "Square seat, four legs, framed back. Dining or counter height. The indoor chair — not an Adirondack.",
  image: "/catalog/lattice-chair.svg",
  overall: { w: 18.5, d: 20.5, h: 40 },
  thickness: 0.75,
  defaultSpecies: "poplar",
  defaultRoute: "pocket",
  indoor: true,
  drawing: {
    family: "chair",
    backStyle: "lattice",
    hasArms: false,
    hasFootring: true,
    seatShape: "square",
    reclined: false,
    seatHeightRatio: 0.61,
  },
  interpretation:
    "A painted lattice-back chair: square seat, four square legs, a box of stretchers, and a framed back with a diamond lattice. Counter height as drawn (seat ~24½\"). Drop overall height to ~36\" and lock the front legs to 17¼\" for dining height. This is not a reclined outdoor chair.",
  confidence: 0.86,
  uncertainties: [
    "Seat height is inferred. Counter stools sit ~24–26\"; dining chairs ~17–18\". Measure the one in the room.",
    "Lattice strip count varies. We spec eight ¾ × ⅜ strips, half-lapped.",
    "Leg stock may be 1½\" or 1¾\" square — confirm before ripping.",
    "Paint-grade poplar is assumed. If the original is MDF or rubberwood, still build it in solid.",
  ],
  stack: [
    "Overall 18½ W × 20½ D × 40 H (counter)",
    "Seat height 24½\" — top of seat",
    "Front legs 23¾\" (seat sits on them)",
    "Back stiles 40\" — legs continue as the back frame",
    "Legs 1¾\" square",
    "Stretchers 1¾\" wide, ~8\" off the floor (footring)",
    "Back opening ~13\" × 14½\" for the lattice",
    "Lattice strips ¾ × ⅜, half-lapped on the diamond",
  ],
  routes: [
    {
      id: "pocket",
      name: "Pocket-screw frame, glued lattice",
      recommendedRank: "beginner",
      summary:
        "Stretchers and seat screw into the legs from the inside. Lattice is glued and pinned in the back frame. Paint hides a lot. The chair that gets used this month.",
      joinery:
        "Pocket holes + glue on stretchers and seat. Half-lap lattice, glue and 23-ga pins. Corner blocks under the seat.",
      tools: ["Kreg jig", "miter saw", "drill", "clamps", "sander"],
      tradeoffs:
        "Pocket holes on the inside of the legs. Fine on a painted chair. Not a period piece.",
      hiddenWork:
        "Corner blocks under the seat. Lattice half-laps you only see if you look for them.",
    },
    {
      id: "mortise",
      name: "Mortise-and-tenon frame, half-lapped lattice",
      recommendedRank: "craftsman",
      summary:
        "Haunched tenons on every stretcher and both back rails. Lattice half-lapped and glued in the opening. The chair that outlives the paint.",
      joinery:
        "M&T stretchers and rails. Half-lapped lattice. Seat in a rabbet or on corner blocks, not glued around.",
      tools: ["Mortiser or chisels", "tenon saw", "marking gauge", "plane"],
      tradeoffs:
        "A full weekend in joinery. Worth it in walnut or oak. Overkill in painted poplar — unless you want the practice.",
      hiddenWork: "Haunches at the top of the front-leg mortises. Lattice laps inside the frame.",
    },
  ],
  parts: [
    {
      id: "seat",
      letter: "A",
      name: "Seat",
      qty: 1,
      length: D(-3.5),
      width: W(-1.5),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "1×8 glue-up, then square",
      notes:
        "Grain front-to-back. Glue two 1×8s, then cut square. Slight radius on the front edge. Not a circle.",
    },
    {
      id: "front-leg",
      letter: "B",
      name: "Front leg",
      qty: 2,
      length: F(23.75),
      width: F(1.75),
      thickness: F(1.75),
      stock: "solid",
      grain: "length",
      fromStock: "8/4 ripped to 1¾\" square, or glue-up",
      notes:
        "Batch-cut to identical length. A chair with one short leg rocks forever. Optional light taper on the two inside faces, top 4\" stays full.",
    },
    {
      id: "back-leg",
      letter: "C",
      name: "Back leg / stile",
      qty: 2,
      length: H(0),
      width: F(1.75),
      thickness: F(1.75),
      stock: "solid",
      grain: "length",
      fromStock: "8/4 ripped to 1¾\" square",
      notes:
        "These are the back legs AND the stiles. Full height. Seat meets them ~24½\" off the floor. Keep them coplanar.",
    },
    {
      id: "side-stretcher",
      letter: "D",
      name: "Side stretcher",
      qty: 2,
      length: D(-3.5),
      width: F(1.75),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "1×3",
      notes: "Between the legs, ~8\" off the floor. This is the footring on the sides.",
    },
    {
      id: "front-stretcher",
      letter: "E",
      name: "Front stretcher",
      qty: 1,
      length: W(-3.5),
      width: F(1.75),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "1×3",
      notes: "The footring you actually put your feet on. Same height as the sides.",
    },
    {
      id: "rear-stretcher",
      letter: "F",
      name: "Rear stretcher",
      qty: 1,
      length: W(-3.5),
      width: F(1.75),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "1×3",
      notes: "Closes the box. Same height. Don't skip it — the frame racks without it.",
    },
    {
      id: "top-rail",
      letter: "G",
      name: "Top back rail",
      qty: 1,
      length: W(-3.5),
      width: F(2.5),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "1×3",
      notes: "Between the stiles at the top. A shallow crest is optional; a straight rail is honest.",
    },
    {
      id: "bottom-rail",
      letter: "H",
      name: "Bottom back rail",
      qty: 1,
      length: W(-3.5),
      width: F(2),
      thickness: F(0.75),
      stock: "solid",
      grain: "length",
      fromStock: "1×3",
      notes: "Just above the seat. The lattice lands in this opening, not on the seat.",
    },
    {
      id: "lattice",
      letter: "J",
      name: "Lattice strip",
      qty: 8,
      length: F(14),
      width: F(0.75),
      thickness: F(0.375),
      stock: "solid",
      grain: "length",
      fromStock: "1×4 ripped, then resawn or planed to ⅜\"",
      notes:
        "Cut long, then fit to the opening on 45°. Half-lap where they cross. Glue and pin. Trim flush to the frame after it dries.",
    },
  ],
  hardware: [
    {
      id: "kreg-chair",
      name: "Pocket-hole screws",
      qty: 32,
      spec: "1¼\" fine-thread #8, square drive",
      aisle: "Kreg / wood joinery",
      where:
        "Two per stretcher end into the legs (inside face). Four through the seat into each front leg. Two into each back stile from the seat underside.",
      forRoutes: ["pocket"],
    },
    {
      id: "corner-blocks",
      name: "Corner blocks",
      qty: 4,
      spec: "¾\" × ¾\" × ~4\", with #8 × 1¼\" screws",
      aisle: "Cut from scrap, or chair-corner hardware",
      where:
        "Under the seat at each corner, screwed into the seat and into the adjacent legs. This is what keeps the seat from racking off the legs.",
    },
    {
      id: "glue-ch",
      name: "Wood glue",
      qty: 1,
      spec: "Titebond II, 8 oz",
      aisle: "Adhesives",
      where:
        "Every stretcher-to-leg joint, the seat glue-up, every lattice half-lap, and the back-rail joints. Not a film on the seat-to-leg joint if you want to recut later — screws and blocks carry that.",
    },
    {
      id: "pins-ch",
      name: "23-ga pins or ⅝\" brads",
      qty: 1,
      spec: "Box of ⅝\" pins",
      aisle: "Fasteners",
      where: "Lattice crossings and lattice-to-frame while the glue sets. Fill and paint.",
    },
    {
      id: "primer-ch",
      name: "Primer + enamel",
      qty: 1,
      spec: "Bonding primer and waterborne enamel, quart of each",
      aisle: "Paint",
      where:
        "Whole chair. Poplar drinks primer. Sand 180, prime, sand 220, two color coats. The original was white.",
    },
  ],
  steps: [
    {
      id: "sc1",
      title: "Mill the legs first",
      body: "Rip 8/4 (or glue ¾ to ¾) to 1¾\" square. Joint and plane so all four read the same. Cut the two front legs together, then the two back stiles together. Mark face sides. A chair is a box — if the legs disagree, the seat will.",
      techniques: ["square-cut"],
    },
    {
      id: "sc2",
      title: "Glue the seat",
      body: "Two 1×8s, grain front to back, jointed edges. Cauls. Square the panel after it dries, then radius the front edge a hair. This is a square seat. Do not cut a circle in it.",
      techniques: ["glue-up"],
    },
    {
      id: "sc3p",
      title: "Pocket the stretchers and dry-fit the box",
      body: "Two pockets on each stretcher end, inside face. Set the jig to actual ¾\". Dry-fit front legs + side stretchers + back stiles, then close with the front and rear stretchers. Diagonals at the floor and at the seat. Then glue.",
      techniques: ["pocket-hole", "clamp-up"],
      forRoutes: ["pocket"],
    },
    {
      id: "sc3m",
      title: "Mortise the legs, tenon the stretchers and rails",
      body: "Mortises land so the stretchers sit ~8\" off the floor. Back-rail mortises in the stiles: bottom rail just above the seat, top rail at the top. Dry-fit the two sides, then close the box. Haunch the top of the front-leg mortises.",
      techniques: ["mortise-tenon", "clamp-up"],
      forRoutes: ["mortise"],
    },
    {
      id: "sc4",
      title: "Set the seat",
      body: "Seat lands on the front legs and between the stiles. Corner blocks at all four corners, screwed into the seat and the legs. Do not glue the whole seat perimeter — you may want it off later. Check that the chair does not rock.",
      techniques: ["clamp-up"],
    },
    {
      id: "sc5",
      title: "Fit the back rails, then the lattice",
      body: "Rails between the stiles. The opening is the lattice's job. Cut eight strips long, lay them on 45° so they make stacked diamonds, mark the half-laps where they cross, cut the laps, glue and pin in the opening. Trim flush after it dries. This is the chair — the rest is a box with a seat.",
      techniques: ["square-cut", "half-lap"],
    },
    {
      id: "sc6",
      title: "Break edges, prime, paint",
      body: "Ease every edge you will touch — seat front, footring, stiles. Sand 120-180. Prime poplar. Two coats of enamel. The original was white. Leave the underside unfinished if you want the wood to still breathe.",
      techniques: ["finish-paint"],
    },
  ],
  buyBoards: [
    {
      id: "b1",
      label: "BOARD 1",
      stock: "8/4 poplar, 5\" × 8'",
      bdft: 6.7,
      role: "LEGS",
      yields: "B front legs · C back stiles",
      body: "Rip four 1¾\" squares. Front legs from one end, stiles from the rest. One spare square if you blow a cut.",
    },
    {
      id: "b2",
      label: "BOARD 2",
      stock: "1×8 poplar, 8'",
      bdft: 5.3,
      role: "SEAT",
      yields: "A seat glue-up",
      body: "Rip two ~8¼\" pieces, glue, square to the seat. Leftover becomes corner blocks.",
    },
    {
      id: "b3",
      label: "BOARD 3",
      stock: "1×3 poplar, 8'",
      bdft: 2,
      role: "STRETCHERS + RAILS",
      yields: "D sides · E front · F rear · G top rail · H bottom rail",
      body: "Cut stretchers first (they have to match). Rails from the rest. One extra 1×3 on the rack.",
      spare: false,
    },
    {
      id: "b4",
      label: "BOARD 4",
      stock: "1×4 poplar, 6'",
      bdft: 2,
      role: "LATTICE",
      yields: "J eight strips, ¾ × ⅜",
      body: "Rip ¾\" strips, then plane or resaw to ⅜\". Cut long and fit to the opening.",
    },
    {
      id: "b5",
      label: "SPARE",
      stock: "1×3 poplar, 4'",
      bdft: 1,
      role: "SPARE RAIL",
      yields: "If a stretcher splits",
      body: "Do not cut until the working boards are done.",
      spare: true,
    },
  ],
  stillBuy: [
    "Kreg 1¼\" fine-thread #8 (pocket route)",
    "Titebond II, 8 oz",
    "23-ga ⅝\" pins",
    "Bonding primer + white enamel, quarts",
    "#8 × 1¼\" screws for corner blocks",
  ],
  doNotBuy: [
    "Adirondack slat stock — this is not that chair",
    "Round seat blank",
    "Wide arms",
    "Exterior stainless (this one lives indoors)",
    "3/4\" lattice — too fat; ⅜\" reads as the original",
  ],
};
